# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nexus_inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nexus_inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15nexus_inference.proto\x12\x12nexus.inference.v1\"\x90\x02\n\x15\x43hatCompletionRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\x12-\n\x08messages\x18\x05 \x03(\x0b\x32\x1b.nexus.inference.v1.Message\x12I\n\x08metadata\x18\x06 \x03(\x0b\x32\x37.nexus.inference.v1.ChatCompletionRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"q\n\x16\x43hatCompletionResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0e\n\x06output\x18\x04 \x01(\t\x12\x12\n\nlatency_ms\x18\x05 \x01(\x01\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xcc\x01\n\x10InferenceService\x12g\n\x0e\x43hatCompletion\x12).nexus.inference.v1.ChatCompletionRequest\x1a*.nexus.inference.v1.ChatCompletionResponse\x12O\n\x06Health\x12!.nexus.inference.v1.HealthRequest\x1a\".nexus.inference.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nexus_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATCOMPLETIONREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_CHATCOMPLETIONREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CHATCOMPLETIONREQUEST']._serialized_start=46
  _globals['_CHATCOMPLETIONREQUEST']._serialized_end=318
  _globals['_CHATCOMPLETIONREQUEST_METADATAENTRY']._serialized_start=271
  _globals['_CHATCOMPLETIONREQUEST_METADATAENTRY']._serialized_end=318
  _globals['_MESSAGE']._serialized_start=320
  _globals['_MESSAGE']._serialized_end=360
  _globals['_CHATCOMPLETIONRESPONSE']._serialized_start=362
  _globals['_CHATCOMPLETIONRESPONSE']._serialized_end=475
  _globals['_HEALTHREQUEST']._serialized_start=477
  _globals['_HEALTHREQUEST']._serialized_end=492
  _globals['_HEALTHRESPONSE']._serialized_start=494
  _globals['_HEALTHRESPONSE']._serialized_end=526
  _globals['_INFERENCESERVICE']._serialized_start=529
  _globals['_INFERENCESERVICE']._serialized_end=733
# @@protoc_insertion_point(module_scope)
