apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
  namespace: nexus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role
  namespace: nexus
rules:
  - apiGroups: ["argoproj.io"]
    resources:
      - workflows
      - workflowtaskresults
      - workflowtasksets
      - workflowtemplates
      - cronworkflows
      - workfloweventbindings
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow
  namespace: nexus
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: nexus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-role
