apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: nexus-ml-pipeline
  namespace: nexus
spec:
  entrypoint: pipeline
  volumes:
    - name: scripts
      configMap:
        name: nexus-mlops-scripts
        defaultMode: 0555
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  templates:
    - name: pipeline
      steps:
        - - name: data-validation
            template: data-validation
        - - name: quantization
            template: quantization
        - - name: model-registration
            template: model-registration
        - - name: deployment
            template: deployment

    - name: data-validation
      container:
        image: alpine:3.19
        command: ["sh"]
        args:
          - "/scripts/data_validation.sh"
        env:
          - name: DATA_PATH
            value: /workspace/data
        volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: workspace
            mountPath: /workspace

    - name: quantization
      container:
        image: alpine:3.19
        command: ["sh"]
        args:
          - "/scripts/quantization.sh"
        env:
          - name: QUANT_METHOD
            value: "awq"
        volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: workspace
            mountPath: /workspace

    - name: model-registration
      container:
        image: alpine:3.19
        command: ["sh"]
        args:
          - "/scripts/register_model.sh"
        env:
          - name: MODEL_NAME
            value: "nexus-llm"
          - name: MODEL_VERSION
            value: "1"
          - name: MODEL_URI_FILE
            value: /workspace/model_uri.txt
        volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: workspace
            mountPath: /workspace

    - name: deployment
      container:
        image: alpine:3.19
        command: ["sh"]
        args:
          - "/scripts/deploy_model.sh"
        env:
          - name: MODEL_URI_FILE
            value: /workspace/model_uri.txt
        volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: workspace
            mountPath: /workspace
