apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: nexus-ml-pipeline
  namespace: nexus
spec:
  entrypoint: pipeline
  volumes:
    - name: scripts
      configMap:
        name: nexus-mlops-scripts
        defaultMode: 0555
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  templates:
    - name: pipeline
      steps:
        - - name: data-validation
            template: data-validation
        - - name: quantization
            template: quantization
        - - name: model-registration
            template: model-registration
        - - name: deployment
            template: deployment
        - - name: gitops-commit
            template: gitops-commit
        - - name: summary-report
            template: summary-report

    - name: data-validation
      container:
        image: python:3.12-slim
        command: ["python"]
        args:
          - "/scripts/data_validation.py"
        env:
          - name: DATA_PATH
            value: /workspace/data
        volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: workspace
            mountPath: /workspace

    - name: quantization
      container:
        image: python:3.12-slim
        command: ["python"]
        args:
          - "/scripts/quantization.py"
        env:
          - name: QUANT_METHOD
            value: "awq"
        volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: workspace
            mountPath: /workspace

    - name: model-registration
      container:
        image: python:3.12-slim
        command: ["python"]
        args:
          - "/scripts/register_model.py"
        env:
          - name: MODEL_NAME
            value: "nexus-llm"
          - name: MODEL_VERSION
            value: "1"
          - name: MODEL_URI_FILE
            value: /workspace/model_uri.txt
        volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: workspace
            mountPath: /workspace

    - name: deployment
      container:
        image: python:3.12-slim
        command: ["python"]
        args:
          - "/scripts/deploy_model.py"
        env:
          - name: MODEL_URI_FILE
            value: /workspace/model_uri.txt
        volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: workspace
            mountPath: /workspace

    - name: gitops-commit
      container:
        image: python:3.12-slim
        command: ["python"]
        args:
          - "/scripts/gitops_commit.py"
        env:
          - name: MANIFEST_PATH
            value: /workspace/kserve_manifest.yaml
          - name: GITOPS_OUTPUT_DIR
            value: /workspace/gitops
          - name: GITOPS_REPO_URL
            value: ""
          - name: GITOPS_GIT_REF
            value: "main"
          - name: GITOPS_TARGET_PATH
            value: "deployments/kserve/llm-vllm.yaml"
        volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: workspace
            mountPath: /workspace

    - name: summary-report
      container:
        image: python:3.12-slim
        command: ["python"]
        args:
          - "/scripts/summary_report.py"
        volumeMounts:
          - name: scripts
            mountPath: /scripts
          - name: workspace
            mountPath: /workspace
